### ISSUE TITLE
Filter default_pagination should render correct markup

### ISSUE THREAD

**Issue by thaichor** [yoolk/yoolk_liquid#80]
the filter should render correct markup http://getbootstrap.com/components/#pagination
or should create a new filter that support render pager

**Comment by chamnap** [comment]
default_pagination is the code from shopify. There is another written by @radin. It's called `bootstrap_pagination`. https://github.com/yoolk/liquid-rails/blob/master/lib/liquid-rails/filters/paginate_filter.rb#L26
