### ISSUE TITLE
Hide menu MORE if pages less than 6

### ISSUE THREAD

**Issue by radin-reth** [yoolk/yoolk_liquid#88]
![yaskawa electric corp machinery mechanics fabricating in tokyo](https://cloud.githubusercontent.com/assets/5484758/7876262/2f3e1ad4-05f3-11e5-9623-2bb07faf5548.png)

**Comment by chamnap** [comment]
close via https://github.com/yoolk/yoolk_liquid/commit/0c5533fdbaa685e17094b43c9a3bebf03f35166b
